# Generated by Django 4.2.1 on 2023-09-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='category',
            new_name='date',
        ),
    ]
