# Generated by Django 4.2.1 on 2023-07-31 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_image')),
                ('title', models.CharField(max_length=100)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField(null=True, blank=True, default=None)),
                ('hiring_location',models.CharField(max_length=100,default="Londan",null=True, blank=True)),
                ('offered_salary', models.IntegerField(default=70000,null=True, blank=True)),
                ('carrer_level', models.CharField(max_length=20,default="JUN",null=True, blank=True)),
                ('qualification', models.CharField(max_length=20,default="Btech",null=True, blank=True)),
                ('experience', models.CharField(max_length=10,default='2 years',null=True, blank=True)),
                ('quantity', models.CharField(max_length=20,default="1",null=True, blank=True)),
                ('gender',models.CharField(max_length=10,default="Male",null=True, blank=True)),
                ('overview', models.TextField(null=True, blank=True,default="We are Ulite. With a presence in more than 60 countries, we’re a growing global organization that helps amazing companies engage with customers through mobile messaging, email, voice and video.")),
                ('skill_and_experience', models.TextField(default="UI/UX",null=True, blank=True)),
                ('skills', models.SlugField()),
                ('requirements',models.TextField(default="UI/UX",null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
