# Generated by Django 4.2.1 on 2023-09-23 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AddJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="user_image"),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(default="No company", max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="job_video"),
                ),
                ("date_posted", models.DateField(auto_now_add=True)),
                ("closing_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "hiring_location",
                    models.CharField(
                        blank=True, default="Londan", max_length=100, null=True
                    ),
                ),
                ("offered_salary", models.CharField(max_length=100)),
                ("career_level", models.CharField(default="JUN", max_length=20)),
                ("qualification", models.CharField(default="Btech", max_length=20)),
                ("experience", models.CharField(default="2 years", max_length=10)),
                ("quantity", models.CharField(default="1", max_length=20)),
                ("gender", models.CharField(default="Male", max_length=10)),
                (
                    "overview",
                    models.TextField(
                        default="We are Ulite. With a presence in more than 60 countries, we’re a growing global organization that helps amazing companies engage with customers through mobile messaging, email, voice and video."
                    ),
                ),
                ("skill_and_experience", models.TextField(default="UI/UX")),
                ("skills", models.SlugField()),
                ("requirements", models.TextField(default="UI/UX")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
