# Generated by Django 4.2.4 on 2023-08-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='carrer_level',
            field=models.CharField(default='JUN', max_length=20),
        ),
        migrations.AlterField(
            model_name='addjob',
            name='experience',
            field=models.CharField(default='2 years', max_length=10),
        ),
        migrations.AlterField(
            model_name='addjob',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='addjob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image'),
        ),
        migrations.AlterField(
            model_name='addjob',
            name='offered_salary',
            field=models.IntegerField(default=70000),
        ),
        migrations.AlterField(
            model_name='addjob',
            name='overview',
            field=models.TextField(default='We are Ulite. With a presence in more than 60 countries, we’re a growing global organization that helps amazing companies engage with customers through mobile messaging, email, voice and video.'),
        ),
        migrations.AlterField(
            model_name='addjob',
            name='qualification',
            field=models.CharField(default='Btech', max_length=20),
        ),
        migrations.AlterField(
            model_name='addjob',
            name='quantity',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='addjob',
            name='requirements',
            field=models.TextField(default='UI/UX'),
        ),
        migrations.AlterField(
            model_name='addjob',
            name='skill_and_experience',
            field=models.TextField(default='UI/UX'),
        ),
    ]
