# Generated by Django 4.2.4 on 2023-08-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_job', '0005_addjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addjob',
            name='status',
        ),
    ]
