# Generated by Django 4.2.1 on 2023-09-05 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('add_job', '0006_remove_addjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
    ]
