# Generated by Django 4.2.1 on 2023-09-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_job', '0007_alter_addjob_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
