# Generated by Django 4.2.1 on 2023-09-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_job', '0010_alter_addjob_offered_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='company',
            field=models.CharField(default='No company', max_length=100),
        ),
    ]
