# Generated by Django 4.2.4 on 2023-08-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforjob',
            name='carrer_level',
            field=models.CharField(default='Graduction', max_length=20),
        ),
    ]
