# Generated by Django 4.2.4 on 2023-08-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_job', '0002_alter_applyforjob_carrer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
