# Generated by Django 4.2.4 on 2023-08-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_job', '0003_applyforjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyforjob',
            name='status',
        ),
    ]
