# Generated by Django 4.2.4 on 2023-08-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_job', '0005_applyforjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
