# Generated by Django 4.2.4 on 2023-08-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_job', '0006_alter_applyforjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforjob',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='job_video'),
        ),
    ]
