# Generated by Django 4.2.1 on 2023-09-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_job', '0007_applyforjob_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforjob',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
