# Generated by Django 4.2.1 on 2023-09-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_job', '0009_applyforjob_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyforjob',
            name='userDetails',
        ),
    ]
