# Generated by Django 4.2.1 on 2023-09-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_job", "0010_remove_applyforjob_userdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyforjob",
            name="carrer_level",
            field=models.CharField(default="Graduation", max_length=20),
        ),
    ]
