# Generated by Django 4.2.1 on 2023-07-31 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userskills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_buyer',
            new_name='is_client',
        ),
    ]
