# Generated by Django 4.2.4 on 2023-08-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_is_admin_alter_user_is_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
