# Generated by Django 4.2.4 on 2023-08-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
