# Generated by Django 4.2.1 on 2023-09-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_is_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_basic_info',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='categories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='user_image'),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='current_position',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='user_image'),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='video_profile',
            field=models.FileField(blank=True, null=True, upload_to='user_image'),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='year_of_experience',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_basic_info',
            name='your_photo',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='user_image'),
        ),
    ]
